
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: news123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  producer:
    build:
      context: .
    command: python News.py
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: news-articles
    depends_on:
      - kafka

  transformer:
    build:
      context: .
    command: python News_Transformer.py
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_INPUT_TOPIC: news-articles
      KAFKA_OUTPUT_TOPIC: news-transformed
    depends_on:
      - kafka
      - producer

  consumer:
    build:
      context: .
    command: python News_Consumer.py
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: news-transformed
    depends_on:
      - kafka
      - transformer

  db_consumer:
    build:
      context: .
    command: python Db_Consumer.py
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: news-transformed
    depends_on:
      - kafka
      - transformer
      - postgres


volumes:
  pgdata: